CREATE TABLE users (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    user_id CHAR(30) UNIQUE NOT NULL,

    email VARCHAR(50) UNIQUE NOT NULL,
    pwdHash CHAR(60) NOT NULL,

    username VARCHAR(30) NOT NULL,
);